"""Join extracted image pins with pins.yml into a human-readable catalog.
Version facts come from the Dockerfiles (single source of truth); justifications
come from pins.yml. Run without args to write CATALOG.md; --check to verify it."""
from __future__ import annotations

import sys
from pathlib import Path

import check_pins
import extract_pins


def render(root: Path) -> str:
    # `root` is the repo `docker/` dir — the same scan root extract_pins and
    # check_pins.load_pins expect (load_pins reads root/pins/pins.yml).
    pins = check_pins.load_pins(root)
    rows = []
    for p in extract_pins.extract(root):
        meta = pins.get(p.tool, {})
        rows.append(
            f"| {p.tool} | {p.version} | {meta.get('state', '?')} | "
            f"{meta.get('inducing_release') or '—'} | "
            f"{'yes' if meta.get('deterministic') else 'no'} | "
            f"{meta.get('reason', '—')} |"
        )
    body = "\n".join(rows)
    return (
        "# Pin catalog (generated — do not edit)\n\n"
        "Generated by `docker/pins/generate_catalog.py` from the Dockerfiles + "
        "`pins.yml`. Run `docker/pins/generate_catalog.py` to refresh.\n\n"
        "| tool | version | state | inducing release | deterministic | reason |\n"
        "| --- | --- | --- | --- | --- | --- |\n"
        f"{body}\n"
    )


def main(argv: list[str]) -> int:
    # This script lives in docker/pins/; the scan root is the parent docker/ dir
    # and the committed catalog lives alongside pins.yml under pins/.
    root = Path(__file__).resolve().parent.parent
    out = root / "pins" / "CATALOG.md"
    md = render(root)
    if "--check" in argv:
        if out.read_text() != md:
            print("::error::CATALOG.md is stale; run docker/pins/generate_catalog.py", file=sys.stderr)
            return 1
        return 0
    out.write_text(md)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
